from models import Section, Level, Question
from database import db

SECTIONS_DATA = [
    {'name':'IKS',           'icon':'📜', 'description':'Indian Knowledge Systems'},
    {'name':'Computer',      'icon':'💻', 'description':'Technology & Computing'},
    {'name':'English',       'icon':'📖', 'description':'Language & Literature'},
    {'name':'Environment',   'icon':'🌿', 'description':'Nature & Ecology'},
    {'name':'Indian Culture','icon':'🪔', 'description':'Heritage & Traditions'},
    {'name':'Sports',        'icon':'⚽', 'description':'Games & Athletics'},
    {'name':'Sociopolitical','icon':'🏛️', 'description':'Society & Politics'},
]
LEVEL_NAMES = {1:'Beginner',2:'Easy',3:'Medium',4:'Hard',5:'Expert'}

# Format: (question_text, option_a, option_b, option_c, option_d, correct_index)
ALL_QUESTIONS = {
  'IKS':{
    1:[("What is the ancient Indian system of medicine?","Ayurveda","Homeopathy","Naturopathy","Unani",0),
       ("Which mathematician discovered zero?","Aryabhata","Brahmagupta","Bhaskara","Varahamihira",1),
       ("Vedas are divided into how many parts?","Two","Three","Four","Five",2),
       ("'Yoga' literally means in Sanskrit?","Stretch","Unite/Join","Breathe","Meditate",1),
       ("Which text describes ancient town planning?","Arthashastra","Manusmriti","Vastu Shastra","Rigveda",2),
       ("Sushruta is father of?","Astronomy","Surgery","Mathematics","Grammar",1),
       ("Natya Shastra written by?","Valmiki","Bharata Muni","Kalidasa","Patanjali",1),
       ("Nachiketa-Yama dialogue is in which Upanishad?","Chandogya","Brihadaranyaka","Katha","Isha",2),
       ("Panini composed?","Ramayana","Mahabharata","Ashtadhyayi","Arthashastra",2),
       ("Fibonacci sequence in Indian study of?","Dance","Music rhythms","Pingala's Chandahshastra","Painting",2)],
    2:[("Major ancient Indian learning centers?","Only Taxila","Only Nalanda","Both Taxila and Nalanda","Neither",2),
       ("Chess originated in?","China","Egypt","India","Persia",2),
       ("Aryabhata calculated pi to how many decimal places?","2","3","4","5",2),
       ("Charaka Samhita is about?","Architecture","Medicine","Mathematics","Poetry",1),
       ("Decimal number system invented in?","Rome","Greece","India","Arabia",2),
       ("Who formalized Sanskrit grammar?","Patanjali","Panini","Valmiki","Vyasa",1),
       ("Dhrupad is?","A dance form","A classical music style","A painting","A cooking style",1),
       ("Rigveda is primarily?","Laws","Stories","Hymns","Medicines",2),
       ("Atoms described by which philosopher?","Chanakya","Kanada","Gautama","Jaimini",1),
       ("Arthashastra deals with?","Poetry","Statecraft","Mathematics","Astronomy",1)],
    3:[("Who first proposed Earth rotates?","Brahmagupta","Varahamihira","Aryabhata","Bhaskara",2),
       ("64 arts include?","Only music","Only dance","Music, dance, painting and many more","Only literature",2),
       ("Sangam literature is from?","North India","East India","South India","West India",2),
       ("Panchama Veda refers to?","Atharva Veda","Mahabharata","Ramayana","Puranas",1),
       ("Classical dance has how many main forms?","4","6","8","10",2),
       ("Sulba Sutras deal with?","Medicine","Music","Geometry for altar construction","Astronomy",2),
       ("Which text describes diplomacy?","Arthashastra","Manusmriti","Kama Sutra","Natyashastra",0),
       ("Madhyamaka philosophy by?","Shankaracharya","Nagarjuna","Ramanuja","Vallabhacharya",1),
       ("Abhijnanasakuntalam is?","A Vedic hymn","A play by Kalidasa","A medical text","Astronomical work",1),
       ("'Rasa' in Indian art means?","Color","Aesthetic emotion","Rhythm","Proportion",1)],
    4:[("'Vasudhaiva Kutumbakam' means?","India is great","The world is one family","God is everywhere","Knowledge is power",1),
       ("Non-violence in Sanskrit?","Karma","Dharma","Ahimsa","Moksha",2),
       ("Nyaya school focuses on?","Logic and epistemology","Atomic theory","Devotion","Yoga",0),
       ("Brihat Samhita covers?","Medicine only","Various sciences including astronomy","Only poetry","Only math",1),
       ("First epic poem?","Mahabharata","Ramayana","Rigveda","Bhagavad Gita",1),
       ("Anekantavada means?","Non-violence","Many-sidedness of truth","Karma theory","Liberation",1),
       ("Lilavati is a text on?","Astronomy","Mathematics","Poetry","Dance",1),
       ("Dhanvantari is god of?","War","Ayurveda/Medicine","Knowledge","Wealth",1),
       ("Surya Siddhanta is about?","Music","Astronomy","Grammar","Ethics",1),
       ("'Mudra' in dance is?","A costume","A hand gesture","An instrument","A dance step",1)],
    5:[("Brahmi script is ancestor of?","Roman alphabet","Most South Asian scripts","Chinese characters","Arabic",1),
       ("'Prana' means?","Soul","Life force/vital energy","God","Karma",1),
       ("Six Schools of philosophy called?","Vedanta","Shad Darshanas","Agamas","Upanishads",1),
       ("Manusmriti provides?","War strategies","Code of conduct","Astronomy","Poetry",1),
       ("Vishwakarma is divine?","God of fire","Craftsman of the gods","God of death","God of water",1),
       ("'Karma' essentially means?","Fate only","Action and its consequences","Prayer","Meditation",1),
       ("Tansen was musician in whose court?","Ashoka","Chandragupta","Akbar","Shivaji",2),
       ("Indus Valley had advanced?","Only agriculture","Urban planning and drainage","Only art","Only trade",1),
       ("'Dharma' means?","Religion only","Righteous duty and cosmic order","Charity","Meditation",1),
       ("Iron Pillar of Delhi notable for?","Its height","Rust-resistance over 1600 years","Its carvings","Its weight",1)],
  },
  'Computer':{
    1:[("CPU stands for?","Central Processing Unit","Computer Personal Unit","Central Program Utility","Core Processing Unit",0),
       ("Binary system is base?","Base 8","Base 10","Base 2","Base 16",2),
       ("Which is input device?","Monitor","Printer","Keyboard","Speaker",2),
       ("RAM stands for?","Random Access Memory","Read Access Mode","Rapid Action Memory","Remote Access Module",0),
       ("Internet originally known as?","WorldWideWeb","ARPANET","Usenet","Ethernet",1),
       ("HTML stands for?","Hyper Text Markup Language","High Text Mode Link","Home Tool Markup Language","Hyper Transfer Meta Link",0),
       ("Which is NOT a programming language?","Python","Java","HTML","C++",2),
       ("USB stands for?","Universal Serial Bus","Unified System Board","Universal System Bridge","Uniform Serial Board",0),
       ("1 Byte equals how many bits?","4","6","8","16",2),
       ("Windows created by?","Apple","Google","Microsoft","IBM",2)],
    2:[("URL stands for?","Universal Resource Locator","Uniform Resource Locator","United Resource Link","Universal Routing Language",1),
       ("Compiler is used to?","Store data","Convert code to machine language","Print documents","Access internet",1),
       ("OS function is to?","Browse internet","Manage hardware/software","Edit photos","Play games",1),
       ("LIFO data structure?","Queue","Array","Stack","Linked List",2),
       ("Phishing is?","Data backup","Fraudulent attempt to steal info","Network scanning","Virus removal",1),
       ("Email protocol?","HTTP","FTP","SMTP","DNS",2),
       ("GUI stands for?","General User Interface","Graphical User Interface","Global Unified Interface","Generic UI",1),
       ("VLSI belongs to which generation?","2nd","3rd","4th","5th",2),
       ("Open source means?","Expensive software","Freely available source code","Government software","Online-only",1),
       ("DNS stands for?","Domain Name System","Data Network Service","Digital Node Server","Dynamic Network Setup",0)],
    3:[("Firewall is?","Hardware to speed up","Security monitoring network traffic","Data storage","Browser",1),
       ("Cloud computing is?","Weather software","On-demand services over internet","Cooling systems","Aerial transmission",1),
       ("Python used for?","Only web","Data science, AI, web and automation","Only gaming","Only databases",1),
       ("Machine learning is?","Teaching machines to walk","Algorithms improving through experience","Hardware upgrades","Manual programming",1),
       ("SQL used for?","Web design","Managing databases","Image editing","System programming",1),
       ("Encryption means?","Deleting data","Converting data to secure coded format","Backing up","Compressing",1),
       ("WWW stands for?","World Wide Web","World Wireless Web","Wide World Web","World Web Works",0),
       ("Which is NoSQL database?","MySQL","Oracle","MongoDB","PostgreSQL",2),
       ("Bandwidth is?","Internet price","Maximum data transfer rate","Cable length","Server location",1),
       ("Algorithm is?","A programming language","Step-by-step problem-solving procedure","Computer hardware","Internet protocol",1)],
    4:[("API stands for?","Advanced Programming Interface","Application Programming Interface","Automated Process Integration","Application Process Interchange",1),
       ("Recursion is?","Repeating same code","Function calling itself","Type of loop","Error handling",1),
       ("TCP/IP stands for?","Transfer Control Protocol","Transmission Control Protocol/Internet Protocol","Terminal Control Process","Transfer Connection Protocol",1),
       ("Version control used for?","System updates","Tracking and managing code changes","Password management","File compression",1),
       ("Blockchain is?","Type of USB","Distributed ledger technology","Computer processor","Programming framework",1),
       ("IoT stands for?","Internet of Things","Input Output Technology","Integrated Online Tools","Internal Operating Technology",0),
       ("Virtual memory is?","Memory on GPU","Using disk space as RAM extension","Cloud storage","Read-only memory",1),
       ("Agile used in?","Hardware design","Software development","Network setup","Database management",1),
       ("Runtime error is?","Error in planning","Error during program execution","Compilation error","Syntax mistake",1),
       ("DevOps is?","Development software","Combining development and operations practices","A programming language","Server hardware",1)],
    5:[("Quantum computing uses?","Faster traditional bits","Qubits in superposition","Photons only","No electricity",1),
       ("Neural networks modeled after?","Computer circuits","Human brain structure","Network cables","Mathematical equations",1),
       ("Containerization means?","Physical packaging","Packaging software with dependencies","Database storage","Memory allocation",1),
       ("Big Data is?","Large complex datasets beyond traditional tools","Only large file sizes","Only fast processing","Only variety",0),
       ("Edge computing is?","Computing at network periphery near data sources","Extreme high-performance computing","Computing at data center only","Computing on screen edges",0),
       ("CAP theorem covers?","Security principles","Consistency, Availability, Partition tolerance","CPU, Architecture, Performance","Caching policies",1),
       ("Zero-day vulnerability is?","Fixed immediately","Unknown flaw with no patch","Minor bug","Outdated software",1),
       ("Microservices means?","Very small computers","Building apps as independent services","Tiny file systems","Minimal coding",1),
       ("Turing complete means?","Very fast computing","Can simulate any Turing machine computation","Quantum capability","AI-powered",1),
       ("Garbage collection is?","Deleting unwanted files","Automatic memory management","Code cleanup tool","Database maintenance",1)],
  },
  'English':{
    1:[("Habitual actions tense?","Past tense","Future tense","Simple present","Past perfect",2),
       ("Antonym of 'happy'?","Joyful","Elated","Sad","Cheerful",2),
       ("Which is proper noun?","city","river","London","mountain",2),
       ("Haiku originated from?","China","India","Japan","Korea",2),
       ("Romeo and Juliet author?","Charles Dickens","William Shakespeare","Jane Austen","Mark Twain",1),
       ("Simile is?","Comparing using 'is'","Comparison using 'like' or 'as'","Giving human qualities","Exaggeration",1),
       ("Plural of 'child'?","Childs","Children","Childes","Childrens",1),
       ("What describes a verb?","Adjective","Adverb","Pronoun","Conjunction",1),
       ("Autobiography written about?","Another person","Yourself","Fictional character","A place",1),
       ("'Omnivore' means?","Eats only plants","Eats only meat","Eats both plants and animals","Eats nothing",2)],
    2:[("'Wind whispered' is?","Simile","Metaphor","Personification","Alliteration",2),
       ("Sonnet has how many lines?","10","12","14","16",2),
       ("Pride and Prejudice author?","Charlotte Brontë","Jane Austen","Mary Shelley","George Eliot",1),
       ("Irony means?","Direct statement","Saying opposite of what is meant","Repetition of sounds","Exaggeration",1),
       ("'Benevolent' means?","Cruel","Well-meaning and kind","Powerful","Intelligent",1),
       ("Active voice: teacher ___ lesson","taught","was taught by","had been taught","being taught",0),
       ("Preposition shows?","Action","Description","Relationship between words","Naming",2),
       ("Which is NOT a vowel?","a","e","b","i",2),
       ("Oxymoron is?","Contradiction of terms","Repetition of words","Comparison","List of items",0),
       ("Animal Farm genre?","Romance","Allegory/Political satire","Horror","Adventure",1)],
    3:[("Alliteration is?","Repetition of vowel sounds","Repetition of initial consonant sounds","Comparing things","Exaggeration",1),
       ("Protagonist is?","The villain","The narrator","The main character","A minor character",2),
       ("'She had finished before he arrived' is?","Past simple","Past continuous","Past perfect","Present perfect",2),
       ("Fahrenheit 451 author?","George Orwell","Aldous Huxley","Ray Bradbury","Isaac Asimov",2),
       ("Catharsis in literature?","Plot twist","Emotional release in audience","Story climax","Character development",1),
       ("'Ephemeral' means?","Very large","Short-lived","Ancient","Mysterious",1),
       ("Stream of consciousness?","Writing about water","Narrative depicting character's thoughts","Scientific writing","Poetry style",1),
       ("Cliffhanger used to?","Describe scenery","End section with suspense","Introduce character","Conclude story",1),
       ("1984 author?","Aldous Huxley","Ray Bradbury","George Orwell","H.G. Wells",2),
       ("Foreshadowing is?","Flashback technique","Hints of future events","Dark tone","Shadow imagery",1)],
    4:[("Byronic hero is?","Greek warrior","Brooding rebellious romantic protagonist","Medieval knight","Comic character",1),
       ("Canterbury Tales author?","Shakespeare","Milton","Chaucer","Marlowe",2),
       ("Magical realism is?","Fantasy genre","Realistic fiction with magical elements","Horror","Children's literature",1),
       ("Stream of consciousness coined by?","James Joyce","Virginia Woolf","William James","Sigmund Freud",2),
       ("Unreliable narrator?","Speaks too fast","Cannot be fully trusted","Changes language","Describes too much",1),
       ("Denouement is?","The climax","Resolution after climax","Introduction","Rising action",1),
       ("Ulysses author?","Virginia Woolf","T.S. Eliot","James Joyce","D.H. Lawrence",2),
       ("Deus ex machina is?","Machine in story","Unlikely savior resolving plot","Greek chorus","Tragic ending",1),
       ("Enlightenment associated with?","Romanticism","Modernism","Reason and logic","Gothic",2),
       ("Anachronism means?","Time travel story","Something misplaced in time","Ancient writing","Circular plot",1)],
    5:[("Booker Prize for?","Poetry","Best English-language novel","Scientific writing","Journalism",1),
       ("In Medias Res means?","From the beginning","In the middle of action","At the end","With backstory",1),
       ("Garcia Marquez associated with?","Realism","Magical realism","Modernism","Surrealism",1),
       ("Intertextuality is?","Footnotes","Relationships between texts","Writing between lines","Multiple authors",1),
       ("Midnight's Children author?","Arundhati Roy","Vikram Seth","Salman Rushdie","Amitav Ghosh",2),
       ("Künstlerroman is about?","War","Development of an artist","Political revolution","Love story",1),
       ("Free indirect discourse means?","Free speech","Narrator adopting character's thoughts without quotes","Indirect object","Freedom of writing",1),
       ("Bard of Avon is?","John Keats","William Wordsworth","William Shakespeare","John Milton",2),
       ("Postcolonial literature deals with?","Historical fiction","Effects of colonialism on cultures","Fantasy worlds","Science fiction",1),
       ("Gone Girl exemplifies?","Linear narrative","Unreliable narrator","Epic storytelling","Comic relief",1)],
  },
  'Environment':{
    1:[("Layer of gases around Earth?","Hydrosphere","Lithosphere","Atmosphere","Biosphere",2),
       ("Most abundant gas in atmosphere?","Oxygen","Carbon Dioxide","Nitrogen","Argon",2),
       ("Photosynthesis is?","Plants making food using sunlight","Animals eating plants","Water cycle","Rock formation",0),
       ("Renewable energy source?","Coal","Petroleum","Solar energy","Natural gas",2),
       ("Main cause of greenhouse effect?","Ozone layer","Increased CO2 trapping heat","Solar flares","Ocean currents",1),
       ("Largest ocean on Earth?","Atlantic","Indian","Arctic","Pacific",3),
       ("Deforestation means?","Planting trees","Clearing forests","Water pollution","Soil erosion",1),
       ("Apex predator is?","Herbivore","Producer","Top of food chain","Decomposer",2),
       ("Ozone layer protects from?","Rain","UV radiation","Earthquakes","Wind",1),
       ("Carbon cycle refers to?","Carbon's movement through environment","Car exhaust systems","Carbon dating","Bicycle manufacturing",0)],
    2:[("Biodiversity is?","Variety of life forms in area","Bio-fuels","Biological warfare","Bacteria only",0),
       ("Non-renewable resource?","Wind","Solar","Coal","Water",2),
       ("Great Barrier Reef is in?","Brazil","India","Australia","Indonesia",2),
       ("Acid rain caused by?","Heavy rainfall","SO2 and NOx reacting with water","Ocean evaporation","Forest fires",1),
       ("Gas causing most global warming?","Oxygen","Nitrogen","Carbon Dioxide","Helium",2),
       ("Ecosystem includes?","Only animals","Only plants","Living and non-living components","Only humans",2),
       ("Composting is?","Burning waste","Converting organic waste to fertilizer","Chemical treatment","Plastic recycling",1),
       ("Amazon rainforest in?","Africa","South America","Asia","Australia",1),
       ("Endangered species means?","Dangerous animals","Species at risk of extinction","Newly discovered","Invasive species",1),
       ("Water covers what % of Earth?","50%","60%","71%","85%",2)],
    3:[("Eutrophication is?","Water purification","Excess nutrients causing algae bloom","Saltwater intrusion","Water freezing",1),
       ("Paris Agreement limits warming to?","1°C","1.5-2°C","3°C","4°C",1),
       ("Biomagnification is?","Growing bigger organisms","Toxins concentrating up food chain","Microscopy technique","Breeding programs",1),
       ("Most biodiverse region?","Arctic tundra","Tropical rainforests","Deserts","Grasslands",1),
       ("Permafrost is?","Permanent ice glaciers","Permanently frozen ground","Arctic species","Fixed terrain",1),
       ("El Niño refers to?","Wind patterns in Africa","Periodic warming of Pacific","Monsoon system","Atlantic hurricanes",1),
       ("Insects are what % of species?","10%","30%","50%","Over 50%",3),
       ("Carbon sequestration is?","Carbon emission","Capturing and storing CO2","Carbon measurement","Carbon tax",1),
       ("Kyoto Protocol about?","Ocean pollution","Reducing greenhouse gas emissions","Nuclear testing","Trade",1),
       ("Phytoplankton important for?","Decorative purposes","Producing Earth's oxygen","Only fish food","Coral formation",1)],
    4:[("Albedo effect is?","Sun's energy output","Surface reflectivity affecting temperature","Ozone measurement","Ocean color",1),
       ("Planetary boundaries refer to?","Country borders","Safe operating limits for Earth systems","Space limits","Ocean territory",1),
       ("Ocean acidification caused by?","Pollution dumping","Ocean absorbing excess CO2","Thermal pollution","Plastic waste",1),
       ("Agroforestry is?","Chemical farming","Integrating trees with crops and livestock","Urban farming","Ocean farming",1),
       ("IPCC stands for?","International Panel","Intergovernmental Panel on Climate Change","International Policy","Independent Panel",1),
       ("Biophilia is?","Fear of living things","Innate human affinity for living systems","Study of bacteria","Extreme environmentalism",1),
       ("Tragedy of commons?","Common people's problems","Overexploitation of shared resources","Public transport issues","Common diseases",1),
       ("Trophic cascade is?","Waterfall ecosystem","Ripple effects when apex predators removed","Food transport","Energy pyramid",1),
       ("Which biome stores most carbon?","Grasslands","Deserts","Boreal forests/Taiga","Tropical rainforests",2),
       ("Keystone species is?","Most numerous species","Species with disproportionate ecosystem impact","Largest species","Bottom of food chain",1)],
    5:[("Sixth mass extinction refers to?","Sixth ice age","Current rapid biodiversity loss due to humans","Sixth climate event","Sixth earthquake event",1),
       ("Circular economy is?","Round economy","Regenerative system eliminating waste","Circular trade routes","Cyclic depression",1),
       ("Doughnut Economics by?","Food industry","Kate Raworth's sustainable economics","NASA","Olympic economics",1),
       ("Regenerative agriculture is?","GMO farming","Farming that restores ecosystem health","High-tech only","Organic certification only",1),
       ("Ocean dead zones caused by?","Overfishing","Hypoxia from nutrient runoff","Ship traffic","Underwater volcanoes",1),
       ("Solastalgia is?","Solar energy term","Distress from environmental change at home","Climate adaptation","Environmental law",1),
       ("Geoengineering is?","Earth science degree","Deliberate large-scale intervention in Earth's systems","Geological engineering","Mining techniques",1),
       ("Tipping points in climate mean?","Ice cap tips","Critical thresholds triggering irreversible changes","Weather tipping","Economic tipping",1),
       ("Net zero means?","Zero all emissions","Balancing emissions produced with those removed","No fossil fuels","Carbon negative",1),
       ("Biome resilience is?","Biome size","Ecosystem's capacity to absorb disturbance and recover","Species count","Geographic stability",1)],
  },
  'Indian Culture':{
    1:[("How many states does India have?","25","28","29","30",1),
       ("National flower of India?","Rose","Sunflower","Lotus","Marigold",2),
       ("Diwali is festival of?","Colors","Lights","Harvest","Victory",1),
       ("National bird of India?","Sparrow","Parrot","Peacock","Eagle",2),
       ("Bharatanatyam is from?","Kerala","Andhra Pradesh","Tamil Nadu","Karnataka",2),
       ("Holy river in Hinduism?","Amazon","Nile","Ganges","Mississippi",2),
       ("Taj Mahal is in?","Delhi","Jaipur","Agra","Lucknow",2),
       ("Holi celebrates?","Winter solstice","Victory of good over evil and spring","Harvest season","New Year",1),
       ("National anthem of India?","Vande Mataram","Saare Jahan Se Achha","Jana Gana Mana","Jai Hind",2),
       ("Yoga Day celebrated on?","June 5","June 21","August 15","October 2",1)],
    2:[("Festival involving floating lamps?","Holi","Diwali","Dev Deepawali","Navratri",2),
       ("Ajanta caves are in?","Rajasthan","Maharashtra","Gujarat","Madhya Pradesh",1),
       ("Garba dance belongs to?","Punjab","Rajasthan","Gujarat","Maharashtra",2),
       ("Pongal is?","A dance form","Harvest festival of Tamil Nadu","A type of music","A monument",1),
       ("Official languages in Constitution?","14","18","22","28",2),
       ("Sanskrit belongs to which family?","Dravidian","Indo-European","Sino-Tibetan","Austroasiatic",1),
       ("Khajuraho temples famous for?","Their height","Intricate sculptures and architecture","Marble only","Location near water",1),
       ("Oldest scripture of Hinduism?","Bhagavad Gita","Ramayana","Rigveda","Upanishads",2),
       ("Bihu dance is from?","West Bengal","Odisha","Assam","Meghalaya",2),
       ("Rangoli is?","A type of music","Colorful floor art during festivals","Traditional dress","Meditation",1)],
    3:[("Kumbh Mela rotates between how many?","2","3","4","6",2),
       ("Thangka painting is?","Rajasthani miniature","Buddhist scroll painting on silk","Cave paintings","Mughal style",1),
       ("Carnatic music is from?","North India","East India","South India","West India",2),
       ("Jallianwala Bagh massacre in?","Delhi","Mumbai","Amritsar","Lahore",2),
       ("Madhubani painting from?","Madhya Pradesh","Bihar","Rajasthan","Uttar Pradesh",1),
       ("Kathak known for?","Powerful jumps","Intricate footwork and storytelling","Sword movements","Acrobatics",1),
       ("Eid-ul-Fitr marks end of?","Muharram","Ramadan","Hajj pilgrimage","Islamic New Year",1),
       ("Amarnath Yatra is pilgrimage to?","Himalayan cave shrine of Lord Shiva","River Ganges","Mountain peak temple","Coastal shrine",0),
       ("Pashmina is?","A dance form","Fine cashmere wool from Himalayan goats","A type of painting","A musical instrument",1),
       ("Mysore Palace was royal residence of?","Chola","Maratha","Wadiyar","Vijayanagara",2)],
    4:[("Navratri significance?","Nine nights celebrating divine feminine","Nine days of fasting","Festival of colors","Harvest festival",0),
       ("Konark Sun Temple built by?","Ashoka","Akbar","Narasimhadeva I","Chandragupta",2),
       ("Ragas used in?","Carnatic only","Hindustani only","Both Hindustani and Carnatic","Western classical only",2),
       ("'Dharma' primarily means?","Prayer rituals","Righteous living and cosmic order","Giving charity","Temple worship",1),
       ("Chikankari is?","Type of dance","Traditional embroidery from Lucknow","Type of cuisine","Folk painting",1),
       ("Paryushana emphasizes?","Grand celebrations","Fasting, forgiveness, and self-discipline","Community feasts","Pilgrimages",1),
       ("Longest coastline Indian state?","Kerala","Andhra Pradesh","Gujarat","Tamil Nadu",2),
       ("Advaita Vedanta propounded by?","Ramanuja","Madhvacharya","Adi Shankaracharya","Vallabhacharya",2),
       ("Warli painting is from?","Madhya Pradesh","Maharashtra","Odisha","Rajasthan",1),
       ("Panchayati Raj represents?","National government","State government","Local self-government","Federal government",2)],
    5:[("Sangam Age in South India?","10th century CE","300 BCE - 300 CE","Medieval period","Mughal period",1),
       ("Vaishnavism is?","Worship of Shiva","Devotional tradition centered on Vishnu","Goddess worship","Jain practice",1),
       ("Dharma-chakra on flag represents?","Circle of life","24-spoke wheel of law, progress, righteousness","Wheel of fortune","Colonial symbol",1),
       ("Pattachitra is?","A music genre","Traditional cloth scroll painting of Odisha","A cooking style","Embroidery",1),
       ("Devadasi system was?","Domestic service","Temple dancers dedicated to divine service","Royal court only","Agricultural rituals",1),
       ("Bhagavad Gita is part of?","Ramayana","Mahabharata","Puranas","Upanishads",1),
       ("Baul tradition is from?","Punjab","Rajasthan","Bengal","Kerala",2),
       ("Dhrupad in classical music is?","Lightest form","Oldest and most ancient classical music style","Folk music","Film music",1),
       ("Sufi-Bhakti syncretic tradition represents?","Pure Islamic tradition","Pure Hindu tradition","Convergence of Islamic and Hindu devotional traditions","Western influence",2),
       ("Varanasi is significant as?","Political capital","One of world's oldest inhabited cities and pilgrimage center","Industrial hub","Educational center",1)],
  },
  'Sports':{
    1:[("Players in football team?","9","10","11","12",2),
       ("Olympic Games held every?","2","3","4","5",2),
       ("National sport of India?","Cricket","Hockey","Kabaddi","Badminton",1),
       ("Hat-trick in cricket means?","Three runs in one ball","Three wickets in three consecutive balls","Three boundaries","Three sixes",1),
       ("Wimbledon associated with?","Cricket","Golf","Tennis","Badminton",2),
       ("FIFA World Cup every?","2 years","4 years","5 years","6 years",1),
       ("P.V. Sindhu plays?","Tennis","Badminton","Table tennis","Squash",1),
       ("Rings in Olympic flag?","3","4","5","6",2),
       ("Sachin's nickname?","The Wall","Master Blaster","The Legend","God of Cricket",1),
       ("Neeraj Chopra won gold in?","Shot put","Hammer throw","Javelin throw","Discus throw",2)],
    2:[("Most Cricket World Cups?","India","Australia","West Indies","England",1),
       ("Ashes series between?","India and England","Australia and England","India and Australia","South Africa and England",1),
       ("Standard swimming pool lane?","25m or 50m","30m","40m","20m",0),
       ("Tour de France is?","Car race","Horse race","Cycling race","Marathon",2),
       ("Basketball team players?","4","5","6","7",1),
       ("Saina Nehwal plays?","Tennis","Badminton","Squash","Table tennis",1),
       ("Kabaddi originated in?","China","Japan","India","Persia",2),
       ("2024 Summer Olympics were in?","Tokyo","London","Paris","Los Angeles",2),
       ("Penalty shootout used to?","Punish players","Decide winner in tied knockout matches","Goal practice","Referee decision",1),
       ("Mary Kom famous for?","Wrestling","Boxing","Judo","Weightlifting",1)],
    3:[("Grand Slam tennis tournaments?","2","3","4","5",2),
       ("Most Olympic gold medals?","Usain Bolt","Carl Lewis","Michael Phelps","Mark Spitz",2),
       ("IPL founded in?","2006","2007","2008","2009",2),
       ("Cricket invented in?","India","Australia","England","South Africa",2),
       ("Duckworth-Lewis used in?","FIFA penalties","Cricket weather adjustments","Tennis tie-breaks","Swimming timing",1),
       ("Volleyball players each side?","5","6","7","8",1),
       ("Durand Cup associated with?","Hockey","Cricket","Football","Badminton",2),
       ("'The Wall' cricketer?","Sourav Ganguly","VVS Laxman","Rahul Dravid","Anil Kumble",2),
       ("LBW means?","Last Ball Win","Leg Before Wicket","Left Bat Win","Long Ball Wide",1),
       ("Ryder Cup in?","Tennis","Football","Golf","Rugby",2)],
    4:[("Abhinav Bindra won gold in?","2000 Sydney","2004 Athens","2008 Beijing","2012 London",2),
       ("F1 race win points?","15","20","25","30",2),
       ("BCCI stands for?","Board of Cricket Commission of India","Board of Control for Cricket in India","Board of Championship Cricket India","British Cricket Club India",1),
       ("Milkha Singh famous as?","Wrestler","Boxer","Sprinter","Long jumper",2),
       ("Santosh Trophy in?","Hockey","Cricket","Football","Kabaddi",2),
       ("Yo-Yo test is?","Flexibility test","Cardiovascular fitness test","Strength test","Speed test",1),
       ("Sport using shuttlecock?","Tennis","Squash","Badminton","Pickleball",2),
       ("Sumo wrestling originated in?","China","Korea","Mongolia","Japan",3),
       ("Stanley Cup is for?","Baseball","Basketball","Ice Hockey","American Football",2),
       ("'Periodization' in training means?","Playing periodically","Systematic cycling of training variables","Sports calendar","Timing of matches",1)],
    5:[("Sabermetrics originated in?","Fencing","Baseball","Sword fighting","Swimming",1),
       ("Queen in chess controls max squares?","21","27","28","32",1),
       ("Zone defense in basketball?","Man-to-man marking","Defending an area not a player","Full-court press","Defensive timeout",1),
       ("Deaflympics is for?","Visually impaired","Athletes with hearing impairments","Wheelchair users","Intellectual disabilities",1),
       ("WAR in baseball stands for?","Win Against Record","Wins Above Replacement","Win Average Rating","Weighted Average Result",1),
       ("GAA sports are from?","Scotland","Wales","Ireland","France",2),
       ("Fartlek training is?","Speed play mixing fast and slow running","Far distance running","Running backwards","Track intervals only",0),
       ("Periodization means?","Playing periodically","Systematic cycling of training variables over time","Sports calendar planning","Timing of matches",1),
       ("Gaelic football most similar to?","Soccer only","Rugby only","A combination of soccer and rugby","Basketball",2),
       ("Paralympic Games held?","Same year as Olympics","Year after Olympics","Every 2 years","Every 6 years",0)],
  },
  'Sociopolitical':{
    1:[("India's Constitution effective date?","August 15 1947","January 26 1950","November 26 1949","October 2 1948",1),
       ("Father of the Nation of India?","Jawaharlal Nehru","Sardar Patel","Mahatma Gandhi","Subhas Chandra Bose",2),
       ("Democracy literally means?","Rule of king","Rule of rich","Rule of people","Rule of law",2),
       ("United Nations established?","1944","1945","1946","1947",1),
       ("India is a?","Federal state","Unitary state","Sovereign Democratic Republic","Constitutional Monarchy",2),
       ("Preamble begins with?","We the Citizens","We the People of India","India is a Republic","By Parliament",1),
       ("Secularism in India means?","No religion","State treating all religions equally","Religion above state","Atheism",1),
       ("Max Rajya Sabha members?","230","245","250","280",1),
       ("Fundamental Rights in?","Part II","Part III","Part IV","Part V",1),
       ("Who appoints PM?","Parliament","Chief Justice","President","Election Commission",2)],
    2:[("Universal Adult Franchise means?","International citizenship","Right to vote for all adults","UN membership","Global passport",1),
       ("Directive Principles in?","Part II","Part III","Part IV","Part V",2),
       ("RTI Act passed in?","2003","2005","2007","2009",1),
       ("Federalism means?","Single central government","Division of powers between centre and states","Military rule","Religious governance",1),
       ("Judicial review means?","Judges reviewing cases","Courts reviewing constitutionality of laws","Annual review","Judge evaluation",1),
       ("Constitutional head of India?","Prime Minister","Chief Justice","President","Speaker of Lok Sabha",2),
       ("Impeachment of President is?","Election process","Formal process to remove President","Presidential appointment","Swearing in",1),
       ("Planning Commission replaced by?","Finance Commission","NITI Aayog","Economic Advisory Council","Ministry of Planning",1),
       ("Habeas corpus is?","Financial law","Right not to be detained without legal cause","Property rights","Civil contract",1),
       ("Lok Sabha electoral system?","Proportional representation","First-past-the-post","Two-round system","Mixed system",1)],
    3:[("Separation of powers means?","Dividing country territorially","Dividing govt powers among legislature, executive, judiciary","Separating parties","Federal system",1),
       ("Non-Aligned Movement formed by?","G7 nations","Communist bloc","Nations not aligned with major powers","United Nations",2),
       ("Populism is?","Popular music","Political approach claiming to represent people vs elites","Population policies","Voting systems",1),
       ("BRICS includes?","Brazil, Russia, India, China, South Africa","Britain, Russia, Italy, China, Sweden","Bangladesh, Russia, India, Canada, Sudan","Belgium, Russia, Iceland, Czech, Sweden",0),
       ("Affirmative action aims to?","Merit-based selection only","Address historical disadvantages","Reduce government jobs","Increase competition",1),
       ("Civil society refers to?","Government organizations","Organizations outside government and business","Military society","Civil courts",1),
       ("Gerrymandering is?","Fair redistricting","Manipulating electoral boundaries to favor a party","Creating new states","Electoral fraud",1),
       ("Panchsheel Agreement between India and?","Pakistan","USA","China","Soviet Union",2),
       ("Soft power means?","Military power","Influence through culture, diplomacy, values","Economic sanctions","Trade power",1),
       ("India's strategic autonomy means?","Military independence","Not aligning permanently with any power","Isolation policy","Nuclear strategy",1)],
    4:[("Westminster model is?","American presidential system","British parliamentary democracy","French semi-presidential","Swiss direct democracy",1),
       ("Multilateralism means?","Bilateral agreements","Multiple countries cooperating on common issues","Military alliances","Trade unions",1),
       ("Failed state is?","Country with bad economy","State unable to perform basic functions","Country that lost war","State with high crime",1),
       ("Glasnost associated with?","Indian democracy","Soviet openness policy under Gorbachev","Chinese economic policy","European integration",1),
       ("Washington Consensus refers to?","US foreign policy","Economic policy of market liberalization","NATO formation","UN charter",1),
       ("Realpolitik means?","Real democracy","Pragmatic politics based on practical factors","Reality TV politics","Real-time policy",1),
       ("Fourth Estate refers to?","Fourth branch of government","The press/media as societal watchdog","Fourth political party","Property rights",1),
       ("Demographic dividend is?","Population decrease","Economic growth from large working-age population","Census dividend","Population diversity",1),
       ("CTBT aims to?","Ban conventional weapons","Prohibit nuclear test explosions","Limit chemical weapons","Regulate biological testing",1),
       ("Political socialization is?","Making politics social","Developing political attitudes and values","Social media politics","Socialist politics",1)],
    5:[("Epistocracy is?","Democracy enhanced by technology","Rule by those with knowledge/expertise","Elite oligarchy","Scientific governance",1),
       ("Overton Window refers to?","Political window dressing","Range of policies acceptable to mainstream public","Open government policy","Diplomatic opportunity",1),
       ("Technocracy is?","Technology-based economy","Government by technical experts","Tech companies governing","Electronic democracy",1),
       ("R2P in international law means?","Right to protest","Protecting civilians from mass atrocities","Responsibility to pay reparations","Right to privacy",1),
       ("Deliberative democracy is?","Slow decision making","Democracy based on informed discussion and debate","Elite decision making","Delegated authority",1),
       ("Arab Spring refers to?","Weather in Arab world","2010-2012 pro-democracy uprisings in Arab countries","Annual Arab summit","Oil price changes",1),
       ("Asymmetric warfare is?","Naval battles","Conflict between forces of very different strength/tactics","Border disputes","Air vs ground combat",1),
       ("Bandung Conference 1955 significant for?","Cold War nuclear talks","Afro-Asian solidarity and Non-Aligned spirit","UN charter revision","European integration",1),
       ("Hypernationalism is?","Healthy patriotism","Extreme nationalism over individual rights and international cooperation","International nationalism","Digital nationalism",1),
       ("Subsidiarity in governance means?","Financial subsidies","Decisions made at lowest competent level","Subsidiary companies","State subservience to center",1)],
  },
}


def seed_all():
    """Run once on first start — skips if sections already exist."""
    if Section.query.count() > 0:
        return
    print('🌱  Seeding Brain Boost V2 database …')

    for s_data in SECTIONS_DATA:
        section = Section(
            name=s_data['name'], description=s_data['description'], icon=s_data['icon']
        )
        db.session.add(section)
        db.session.flush()

        section_questions = ALL_QUESTIONS.get(s_data['name'], {})

        for lvl_num in range(1, 6):
            level = Level(
                section_id=section.id,
                level_number=lvl_num,
                name=LEVEL_NAMES[lvl_num]
            )
            db.session.add(level)
            db.session.flush()

            for q_tuple in section_questions.get(lvl_num, []):
                q_text, a, b, c, d, correct = q_tuple
                db.session.add(Question(
                    level_id=level.id, question_text=q_text,
                    option_a=a, option_b=b, option_c=c, option_d=d,
                    correct_option=correct
                ))

    db.session.commit()
    print('✅  Seeding complete! 350 questions loaded.')
